[components]

[components.celestia]

[components.celestia.light]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"

[components.celestia.bridge]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"


[components.avail]

[components.avail.light]
binary = "avail-light"
download = "/tmp/vimana/avail/init.sh"


[components.gmworld]

[components.gmworld.da]
binary = "gmworld-da"
download = "/home/ankit/vimana/scripts/rollup_init.sh"

[components.gmworld.rollup]
binary = "gmworld-rollup"
download = "/home/ankit/vimana/scripts/rollup_mocha.sh"

# [components.berachain]

# [components.berachain.full]
# binary = "/path/to/celestia/binary"
# download = "https://example.com/berachain.zip"
