[components]

[components.celestia]

[components.celestia.light]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"

[components.celestia.bridge]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"


[components.avail]

[components.avail.light]
binary = "avail-light"
download = "/home/ankit/vimana/scripts/nostream.sh"


[components.nostream]

[components.nostream.nostream]
binary = "nostream"
download = "/home/ankit/vimana/scripts/nostream.sh"

# [components.berachain]

# [components.berachain.full]
# binary = "/path/to/celestia/binary"
# download = "https://example.com/berachain.zip"
