[components]

[components.celestia]

[components.celestia.light]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"

[components.celestia.bridge]
binary = "/tmp/vimana/celestia/celestia"
download = "/tmp/vimana/celestia/init.sh"


[components.avail]

[components.avail.light]
binary = "avail-light"
download = "/tmp/vimana/avail/init.sh"


[components.rollup]

[components.rollup.init]
binary = "rollup-init"
download = "/home/chappie/vimana/scripts/rollup_init.sh"

[components.rollup.start]
binary = "rollup-start"
download = "/home/chappie/vimana/scripts/rollup_mocha.sh"

# [components.berachain]

# [components.berachain.full]
# binary = "/path/to/celestia/binary"
# download = "https://example.com/berachain.zip"
