[components]

[components.celestia]

[components.celestia.light]
binary = "/usr/local/bin/celestia"
download = "/tmp/vimana/celestia/init.sh"

[components.celestia.bridge]
binary = "/usr/local/bin/celestia"
download = "/tmp/vimana/celestia/init.sh"

[components.avail]

[components.avail.light]
binary = "avail-light"
download = "/tmp/vimana/avail/init.sh"
