[spacecores]

[spacecores.celestia]

[spacecores.celestia.light]
binary = "/usr/local/bin/celestia"
download = "/tmp/vimana/celestia/init.sh"

[spacecores.celestia.bridge]
binary = "/usr/local/bin/celestia"
download = "/tmp/vimana/celestia/init.sh"

[spacecores.avail]

[spacecores.avail.light]
binary = "avail-light"
download = "/tmp/vimana/avail/init.sh"
